<?xml version="1.0"?>

<robot name="sensor_scan" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="distancex" value="0.04" />
  <xacro:property name="distancey" value="0.04" />
  <xacro:property name="distancez" value= "0.02"/>

  <!-- sensor joint -->
  <joint name="fixed_sensor_scan" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_scan"/>
    <origin xyz = "0.33 0 0.07"/>
  </joint>

  <!-- sensor Link -->
  <link name="sensor_scan">
    <visual>
      <origin xyz="0 0 ${distancez/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${distancex} ${distancey} ${distancez}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${distancez/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${distancex} ${distancey} ${distancez}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${distancez/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="sensor_scan">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="sensor_scan">
    <sensor name="laser" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>180</samples>
            <resolution>1.000000</resolution>
            <min_angle>1.5708</min_angle>
            <max_angle>-1.5708</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.25</min>
          <max>5.0</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>sensor_scan</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
