axis_linear: 1
scale_linear: 2
scale_linear_turbo: 100

axis_angular: 0
scale_angular: 4

enable_button: 1  # L2 shoulder button
enable_turbo_button: 3  # L1 shoulder button
autorepeat_rate: 20  # Añadido el valor de autorepeat_rate como un entero
